export SHELL="/data/data/com.termux/files/usr/bin/bash"
export PREFIX="/data/data/com.termux/files/usr"
export PWD="/data/data/com.termux/files/home"
export EXTERNAL_STORAGE="/sdcard"
export LD_PRELOAD="/data/data/com.termux/files/usr/lib/libtermux-exec.so"
export HOME="/data/data/com.termux/files/home"
export LANG="en_US.UTF-8"
export TMPDIR="/data/data/com.termux/files/usr/tmp"
export ANDROID_DATA="/data"
export TERM="xterm-256color"
export SHLVL="1"
export ANDROID_ROOT="/system"
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export PATH="/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets"
export _="/data/data/com.termux/files/usr/bin/env"
bash